"""Add workspace_id and role to user

Revision ID: af33b4f1562a
Revises: c0237ad68512
Create Date: 2026-08-25 16:37:32.345129

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'af33b4f1562a'
down_revision = 'c0237ad68512'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('workspace_id', sa.Uuid(), nullable=True))
    op.add_column('user', sa.Column('role', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_user_workspace_id'), 'user', ['workspace_id'], unique=False)
    op.create_foreign_key(
        "user_workspace_id_fkey",
        "user",
        "workspace",
        ["workspace_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("user_workspace_id_fkey", "user", type_="foreignkey")
    op.drop_index(op.f('ix_user_workspace_id'), table_name='user')
    op.drop_column('user', 'role')
    op.drop_column('user', 'workspace_id')
    # ### end Alembic commands ###
